<?php

namespace Database\Seeders;

use App\Models\Kendaraan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KendaraanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('kendaraans')->delete();
$data = [
        ['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1157 CF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1283 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1162 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1432 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1069 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1149 CF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1172 OF', 'perusahaan_id' => 2, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1262 OF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1236 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1284 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1043 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1037 CF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1485 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1134 BF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1070 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1322 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1418 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1442 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1265 OF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1091 CF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1427 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1158 OF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1108 BF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1081 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1399 BF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1294 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1079 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1273 CF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1049 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1078 CF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1330 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1328 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1279 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1006 OF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1329 BF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1387 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1239 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1230 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1318 OF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1062 BF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'RIKI SANJAYA ', 'no_kendaraan' => 'AA 1196 BF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1267 OF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1350 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1368 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1307 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1373 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1403 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1266 OF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1126 BF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1237 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1243 OF', 'perusahaan_id' => 4, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1263 BF', 'perusahaan_id' => 4, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1409 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1355 OF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1160 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1047 CF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1369 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1242 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1176 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1198 OF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1392 CF', 'perusahaan_id' => 4, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1209 CF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1311 OF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1348 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1550 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1334 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1343 OF', 'perusahaan_id' => 4, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1410 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUSHOLIYAN', 'no_kendaraan' => 'AA 1377 OF', 'perusahaan_id' => 5, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1253 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1164 CF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1297 OF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1050 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1338 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1002 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1003 DF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1183 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1195 CF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1405 OF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1395 CF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1394 CF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1012 DF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1312 CF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1195 CF', 'perusahaan_id' => 1, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1030 OF', 'perusahaan_id' => 3, 'trayek_id' => 1],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1486 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1220 CF', 'perusahaan_id' => 6, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1292 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1259 BF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1132 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1138 CF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1362 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1093 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1106 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1391 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'KHOIRULLAH', 'no_kendaraan' => 'AA 1217 BF', 'perusahaan_id' => 7, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1156 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1201 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1372 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1357 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1429 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1489 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1249 CF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1169 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1024 OF', 'perusahaan_id' => 1, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1268 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1293 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1218 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1203 oF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1108 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1364 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1219 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1358 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1479 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1407 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1447 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1094 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1216 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1264 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'ANDIK APRILLIYANTO', 'no_kendaraan' => 'AA 1421 OF', 'perusahaan_id' => 8, 'trayek_id' => 2],
['pemilik' => 'ANDIK APRILLIYANTO', 'no_kendaraan' => 'AA 1413 OF', 'perusahaan_id' => 8, 'trayek_id' => 2],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1376 OF', 'perusahaan_id' => 1, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1263 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'SUPIYAN ', 'no_kendaraan' => 'AA 1020 OF', 'perusahaan_id' => 9, 'trayek_id' => 2],
['pemilik' => 'SUPIYAN ', 'no_kendaraan' => 'AA 1021 OF', 'perusahaan_id' => 9, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1107 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1371 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1319 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1335 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1361 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1106 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1336 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1157 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1104 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1103 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1005 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1096 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1120 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1124 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1217 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1195 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1357 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1210 CF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1203 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1196 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1193 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1095 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1224 OF', 'perusahaan_id' => 3, 'trayek_id' => 2],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1231 CF', 'perusahaan_id' => 1, 'trayek_id' => 2],
['pemilik' => 'ANDIK APRILLIYANTO', 'no_kendaraan' => 'AA 1033 DF', 'perusahaan_id' => 10, 'trayek_id' => 2],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1068 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1055 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1084 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUSHOLIYAN', 'no_kendaraan' => 'AA 1496 OF', 'perusahaan_id' => 11, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1437 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1322 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1080 CF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1039 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1197 OF', 'perusahaan_id' => 3, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1056 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1021 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1463 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1315 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1314 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1332 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1247 BF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1374 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1351 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'SUMAJI', 'no_kendaraan' => 'AA 1260 OF', 'perusahaan_id' => 12, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1225 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'SUMAJI', 'no_kendaraan' => 'AA 1513 OF', 'perusahaan_id' => 12, 'trayek_id' => 3],
['pemilik' => 'SUMAJI', 'no_kendaraan' => 'AA 1259 OF', 'perusahaan_id' => 12, 'trayek_id' => 3],
['pemilik' => 'SUMAJI', 'no_kendaraan' => 'AA 1126 CF', 'perusahaan_id' => 12, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1057 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1036 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1308 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1194 OF', 'perusahaan_id' => 3, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1506 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1301 OF', 'perusahaan_id' => 6, 'trayek_id' => 3],
['pemilik' => 'SUMAJI', 'no_kendaraan' => 'AA 1261 OF', 'perusahaan_id' => 12, 'trayek_id' => 3],
['pemilik' => 'SUPRIYONO ', 'no_kendaraan' => 'AA 1457 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1340 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'SUPRIYONO ', 'no_kendaraan' => 'AA 1120 BF', 'perusahaan_id' => 13, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1285 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1101 CF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1102 CF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1440 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1495 OF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1165 BF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1021 DF', 'perusahaan_id' => 4, 'trayek_id' => 3],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1139 OF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'SUPIYAN', 'no_kendaraan' => 'AA 1099 OF', 'perusahaan_id' => 14, 'trayek_id' => 4],
['pemilik' => 'SUPIYAN', 'no_kendaraan' => 'AA 1027 OF', 'perusahaan_id' => 14, 'trayek_id' => 4],
['pemilik' => 'H.BADRUN', 'no_kendaraan' => 'AA 1154 CF', 'perusahaan_id' => 15, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1109 CF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'H.BADRUN', 'no_kendaraan' => 'AA 1426 OF', 'perusahaan_id' => 15, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1494 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1054 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1210 BF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1340 BF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1115 CF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1353 BF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1016 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'AHMAD SYAKDUN ', 'no_kendaraan' => 'AA 1257 BF', 'perusahaan_id' => 17, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI (SEMULA MUSHOLIYAN)', 'no_kendaraan' => 'AA 1231 OF', 'perusahaan_id' => 18, 'trayek_id' => 4],
['pemilik' => 'MUSHOLIYAN', 'no_kendaraan' => 'AA 1316 OF', 'perusahaan_id' => 19, 'trayek_id' => 4],
['pemilik' => 'DWI HARYADI ', 'no_kendaraan' => 'AA 1064 OF', 'perusahaan_id' => 14, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1342 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1280 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1451 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1423 OF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1321 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1071 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1073 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1088 OF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1042 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'SUPIYAN', 'no_kendaraan' => 'AA 1029 OF', 'perusahaan_id' => 14, 'trayek_id' => 4],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1187 OF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1063 CF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1140 OF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1143 OF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1510 OF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1146 OF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1142 OF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1509 OF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'H. M BADRUN ', 'no_kendaraan' => 'AA 1009 OF', 'perusahaan_id' => 20, 'trayek_id' => 4],
['pemilik' => 'H. M BADRUN ', 'no_kendaraan' => 'AA 1012 OF', 'perusahaan_id' => 20, 'trayek_id' => 4],
['pemilik' => 'H. M BADRUN ', 'no_kendaraan' => 'AA 1008 OF', 'perusahaan_id' => 20, 'trayek_id' => 4],
['pemilik' => 'MUSHOLIYAN', 'no_kendaraan' => 'AA 1262 BF', 'perusahaan_id' => 19, 'trayek_id' => 4],
['pemilik' => 'MUSHOLIYAN', 'no_kendaraan' => 'AA 1443 OF', 'perusahaan_id' => 19, 'trayek_id' => 4],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1031 CF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1319 BF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'SUPIYAN', 'no_kendaraan' => 'AA 1026 OF', 'perusahaan_id' => 14, 'trayek_id' => 4],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1136 OF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1098 OF', 'perusahaan_id' => 3, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1424 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'SUPIYAN', 'no_kendaraan' => 'AA 1052 CF', 'perusahaan_id' => 14, 'trayek_id' => 4],
['pemilik' => 'MUSHOLIYAN', 'no_kendaraan' => 'AA 1397 OF', 'perusahaan_id' => 19, 'trayek_id' => 4],
['pemilik' => 'MUSHOLIYAN', 'no_kendaraan' => 'AA 1396 OF', 'perusahaan_id' => 19, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1388 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1095 CF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1145 OF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1477 OF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1342 BF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1395 OF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'ANTONIUS SURYONO', 'no_kendaraan' => 'AA 1317 OF', 'perusahaan_id' => 21, 'trayek_id' => 4],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1325 OF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'H. M BADRUN ', 'no_kendaraan' => 'AA 1449 OF', 'perusahaan_id' => 20, 'trayek_id' => 4],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1270 OF', 'perusahaan_id' => 22, 'trayek_id' => 4],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1087 OF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1137 OF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1192 BF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1281 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'SUDIYONO ', 'no_kendaraan' => 'AA 1227 CF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'SUDIYONO ', 'no_kendaraan' => 'AA 1282 OF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1149 OF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'SUPIYAN', 'no_kendaraan' => 'AA 1018 OF', 'perusahaan_id' => 14, 'trayek_id' => 4],
['pemilik' => 'SUPIYAN ', 'no_kendaraan' => 'AA 1445 OF', 'perusahaan_id' => 20, 'trayek_id' => 4],
['pemilik' => 'SUPIYAN ', 'no_kendaraan' => 'AA 1017 OF', 'perusahaan_id' => 14, 'trayek_id' => 4],
['pemilik' => 'SUPIYAN ', 'no_kendaraan' => 'AA 1019 OF', 'perusahaan_id' => 14, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1092 OF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 1193 CF', 'perusahaan_id' => 16, 'trayek_id' => 4],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1520 OF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1137 OF', 'perusahaan_id' => 6, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1302 OF', 'perusahaan_id' => 4, 'trayek_id' => 4],
['pemilik' => 'SUPIYAN', 'no_kendaraan' => 'AA 1028 OF', 'perusahaan_id' => 14, 'trayek_id' => 4],
['pemilik' => 'H.BADRUN', 'no_kendaraan' => 'AA 1013 OF', 'perusahaan_id' => 20, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1398 CF', 'perusahaan_id' => 1, 'trayek_id' => 4],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1014 OF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1065 OF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1175 OF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1063 OF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1060 OF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'ANTONIUS SURYONO', 'no_kendaraan' => 'AA 1385 BF', 'perusahaan_id' => 21, 'trayek_id' => 5],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1269 OF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'SUPIYAN', 'no_kendaraan' => 'AA 1022 OF', 'perusahaan_id' => 14, 'trayek_id' => 5],
['pemilik' => 'H CHADSIQ MF ', 'no_kendaraan' => 'AA 1233 CF', 'perusahaan_id' => 23, 'trayek_id' => 5],
['pemilik' => 'H CHADSIQ MF ', 'no_kendaraan' => 'AA 1162 CF', 'perusahaan_id' => 23, 'trayek_id' => 5],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1044 CF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1363 OF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1326 BF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1173 CF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1191 CF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1347 OF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'SUWARNO ', 'no_kendaraan' => 'AA 1159 OF', 'perusahaan_id' => 3, 'trayek_id' => 5],
['pemilik' => 'SUYANTI ', 'no_kendaraan' => 'AA 1343 BF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'SUYANTI ', 'no_kendaraan' => 'AA 1219 CF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1365 OF', 'perusahaan_id' => 6, 'trayek_id' => 5],
['pemilik' => 'TAUFIQURROMAN ', 'no_kendaraan' => 'AA 1433 OF', 'perusahaan_id' => 23, 'trayek_id' => 5],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1472 OF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'SUPIYAN ', 'no_kendaraan' => 'AA 1023 OF', 'perusahaan_id' => 14, 'trayek_id' => 5],
['pemilik' => 'ANTONIUS SURYONO', 'no_kendaraan' => 'AA 1178 OF', 'perusahaan_id' => 24, 'trayek_id' => 5],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1174 CF', 'perusahaan_id' => 1, 'trayek_id' => 5],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1406 OF', 'perusahaan_id' => 25, 'trayek_id' => 5],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1251 BF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1246 BF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1114 CF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1193 BF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1161 CF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1069 CF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1474 OF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1131 BF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1153 OF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1232 OF', 'perusahaan_id' => 1, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1342 CF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1295 BF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1204 OF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1160 CF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1123 OF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1090 OF', 'perusahaan_id' => 26, 'trayek_id' => 6],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1015 OF', 'perusahaan_id' => 1, 'trayek_id' => 6],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1256 BF', 'perusahaan_id' => 1, 'trayek_id' => 6],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1152 OF', 'perusahaan_id' => 1, 'trayek_id' => 6],
['pemilik' => 'A MUTHOLIB', 'no_kendaraan' => 'AA 1241 BF', 'perusahaan_id' => 27, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1051 BF', 'perusahaan_id' => 4, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1428 OF', 'perusahaan_id' => 4, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1260 BF', 'perusahaan_id' => 4, 'trayek_id' => 7],
['pemilik' => 'HARYONO', 'no_kendaraan' => 'AA 1052 CF', 'perusahaan_id' => 28, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1050 BF', 'perusahaan_id' => 1, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1180 OF', 'perusahaan_id' => 1, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1074 OF', 'perusahaan_id' => 4, 'trayek_id' => 7],
['pemilik' => 'MASNGUD', 'no_kendaraan' => 'AA 1542 CF', 'perusahaan_id' => 29, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1042 CF', 'perusahaan_id' => 1, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1312 OF', 'perusahaan_id' => 30, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1449 OF', 'perusahaan_id' => 30, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1249 OF', 'perusahaan_id' => 4, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1158 CF', 'perusahaan_id' => 30, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1229 OF', 'perusahaan_id' => 4, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1324 OF', 'perusahaan_id' => 4, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1035 OF', 'perusahaan_id' => 1, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1067 OF', 'perusahaan_id' => 4, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1121 CF', 'perusahaan_id' => 4, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1321 BF', 'perusahaan_id' => 4, 'trayek_id' => 7],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1033 CF', 'perusahaan_id' => 1, 'trayek_id' => 7],
['pemilik' => 'MASUDQI', 'no_kendaraan' => 'AA 1139 CF', 'perusahaan_id' => 6, 'trayek_id' => 8],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1296 OF', 'perusahaan_id' => 4, 'trayek_id' => 8],
['pemilik' => 'GITO PRASAJO C', 'no_kendaraan' => 'AA 1367 BF', 'perusahaan_id' => 31, 'trayek_id' => 8],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1247 OF', 'perusahaan_id' => 6, 'trayek_id' => 8],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1375 BF', 'perusahaan_id' => 4, 'trayek_id' => 8],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1543 CF', 'perusahaan_id' => 6, 'trayek_id' => 8],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1218 CF', 'perusahaan_id' => 6, 'trayek_id' => 8],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1366 BF', 'perusahaan_id' => 6, 'trayek_id' => 8],
['pemilik' => 'SUPIYAN', 'no_kendaraan' => 'AA 1007 OF', 'perusahaan_id' => 32, 'trayek_id' => 8],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1398 BF', 'perusahaan_id' => 4, 'trayek_id' => 8],
['pemilik' => 'ZAENAL MAARIF', 'no_kendaraan' => 'AA 1369 BF', 'perusahaan_id' => 31, 'trayek_id' => 8],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1048 OF', 'perusahaan_id' => 1, 'trayek_id' => 9],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1172 CF', 'perusahaan_id' => 1, 'trayek_id' => 9],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1364 BF', 'perusahaan_id' => 1, 'trayek_id' => 9],
['pemilik' => 'GITO PRASOJO C', 'no_kendaraan' => 'AA 1372 BF', 'perusahaan_id' => 33, 'trayek_id' => 9],
['pemilik' => 'H NGIZUDIN', 'no_kendaraan' => 'AA 1223 CF', 'perusahaan_id' => 33, 'trayek_id' => 9],
['pemilik' => 'HM RODLI', 'no_kendaraan' => 'AA 1178 CF', 'perusahaan_id' => 33, 'trayek_id' => 9],
['pemilik' => 'JUNAIDI', 'no_kendaraan' => 'AA 1394 BF', 'perusahaan_id' => 33, 'trayek_id' => 9],
['pemilik' => 'PARYONO', 'no_kendaraan' => 'AA 1304 BF', 'perusahaan_id' => 34, 'trayek_id' => 9],
['pemilik' => 'PARYONO', 'no_kendaraan' => 'AA 1130 OF', 'perusahaan_id' => 34, 'trayek_id' => 9],
['pemilik' => 'PUJIANTO', 'no_kendaraan' => 'AA 1363 BF', 'perusahaan_id' => 33, 'trayek_id' => 9],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1176 CF', 'perusahaan_id' => 1, 'trayek_id' => 9],
['pemilik' => 'SLAMET HARYONO', 'no_kendaraan' => 'AA 1132 OF', 'perusahaan_id' => 34, 'trayek_id' => 9],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1401 OF', 'perusahaan_id' => 1, 'trayek_id' => 9],
['pemilik' => 'SUKIRNO', 'no_kendaraan' => 'AA 1278 CF', 'perusahaan_id' => 34, 'trayek_id' => 9],
['pemilik' => 'SUPRIYADI', 'no_kendaraan' => 'AA 1129 OF', 'perusahaan_id' => 34, 'trayek_id' => 9],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1374 BF', 'perusahaan_id' => 1, 'trayek_id' => 9],
['pemilik' => 'ZAENAL MAARIF', 'no_kendaraan' => 'AA 1370 BF', 'perusahaan_id' => 33, 'trayek_id' => 9],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1044 OF', 'perusahaan_id' => 1, 'trayek_id' => 10],
['pemilik' => 'BROTO WARDOYO', 'no_kendaraan' => 'AA 1350 BF', 'perusahaan_id' => 33, 'trayek_id' => 10],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1035 CF', 'perusahaan_id' => 1, 'trayek_id' => 10],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1270 BF', 'perusahaan_id' => 1, 'trayek_id' => 10],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1360 OF', 'perusahaan_id' => 1, 'trayek_id' => 10],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1286 BF', 'perusahaan_id' => 1, 'trayek_id' => 10],
['pemilik' => 'MANSORIP', 'no_kendaraan' => 'AA 1021 BF', 'perusahaan_id' => 33, 'trayek_id' => 10],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1373 BF', 'perusahaan_id' => 1, 'trayek_id' => 10],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1402 OF', 'perusahaan_id' => 1, 'trayek_id' => 10],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1278 BF', 'perusahaan_id' => 1, 'trayek_id' => 10],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1356 OF', 'perusahaan_id' => 1, 'trayek_id' => 10],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1330 BF', 'perusahaan_id' => 1, 'trayek_id' => 10],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1237 BF', 'perusahaan_id' => 1, 'trayek_id' => 10],
['pemilik' => 'ACH SHOLEH', 'no_kendaraan' => 'AA 1230 CF', 'perusahaan_id' => 34, 'trayek_id' => 11],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1196 CF', 'perusahaan_id' => 6, 'trayek_id' => 11],
['pemilik' => 'H HARYONO', 'no_kendaraan' => 'AA 1216 CF', 'perusahaan_id' => 35, 'trayek_id' => 11],
['pemilik' => 'NURSITO', 'no_kendaraan' => 'AA 1091 OF', 'perusahaan_id' => 34, 'trayek_id' => 11],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1139 BF', 'perusahaan_id' => 6, 'trayek_id' => 11],
['pemilik' => 'SUMEDI', 'no_kendaraan' => 'AA 1242 CF', 'perusahaan_id' => 34, 'trayek_id' => 11],
['pemilik' => 'SUPRIYATIN', 'no_kendaraan' => 'AA 1197 CF', 'perusahaan_id' => 35, 'trayek_id' => 11],
['pemilik' => "SYAI'IN", 'no_kendaraan' => 'AA 1240 OF', 'perusahaan_id' => 34, 'trayek_id' => 11],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1335 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1388 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1367 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1085 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1299 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1387 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1250 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1179 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1126 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1351 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1371 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1076 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1164 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1298 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1003 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'ANTONIUS SURYONO', 'no_kendaraan' => 'AA 1278 OF', 'perusahaan_id' => 21, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1339 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1319 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1338 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MISBACHUL MUNIR', 'no_kendaraan' => 'AA 1288 OF', 'perusahaan_id' => 31, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1498 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1368 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1040 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'PRIYONO ROMBAK', 'no_kendaraan' => 'AA 1328 CF', 'perusahaan_id' => 31, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1345 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1330 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1456 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'SRI BANATUN', 'no_kendaraan' => 'AA 1324 CF', 'perusahaan_id' => 31, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1243 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1289 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1038 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1321 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1326 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1320 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'TRI SUGENG R', 'no_kendaraan' => 'AA 1281 CF', 'perusahaan_id' => 31, 'trayek_id' => 12],
['pemilik' => 'TURYANTO', 'no_kendaraan' => 'AA 1325 CF', 'perusahaan_id' => 31, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA      OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1369 CF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1392 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1041 OF', 'perusahaan_id' => 1, 'trayek_id' => 12],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1105 OF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1085 CF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1293 BF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'DIARJO', 'no_kendaraan' => 'AA 1208 CF', 'perusahaan_id' => 33, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1209 OF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1318 CF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1059 OF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1381 OF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1210 OF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'IKA LAILI PARCHATI', 'no_kendaraan' => 'AA 1068 CF', 'perusahaan_id' => 33, 'trayek_id' => 13],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1526 OF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1291 OF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1336 BF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1047 OF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1294 BF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1359 OF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1283 BF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1012 CF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1322 CF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'MUHYANTO', 'no_kendaraan' => 'AA 1480 OF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1292 BF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1404 OF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1004 OF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1086 OF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1027 CF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1165 OF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1310 BF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'ROCHMADLON', 'no_kendaraan' => 'AA 1123 OF', 'perusahaan_id' => 33, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1338 BF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1452 OF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1501 CF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1082 OF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1304 CF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1182 CF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'SUMARNO', 'no_kendaraan' => 'AA 1312 CF', 'perusahaan_id' => 33, 'trayek_id' => 13],
['pemilik' => 'SURADI', 'no_kendaraan' => 'AA 1312 BF', 'perusahaan_id' => 33, 'trayek_id' => 13],
['pemilik' => 'SURADI', 'no_kendaraan' => 'AA 1332 BF', 'perusahaan_id' => 33, 'trayek_id' => 13],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1462 OF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'TUTUR', 'no_kendaraan' => 'AA 1335 BF', 'perusahaan_id' => 33, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1052 OF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1003 OF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1017 CF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'WASIDK', 'no_kendaraan' => 'AA 1022 CF', 'perusahaan_id' => 33, 'trayek_id' => 13],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1539 OF', 'perusahaan_id' => 3, 'trayek_id' => 13],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1083 OF', 'perusahaan_id' => 1, 'trayek_id' => 13],
['pemilik' => 'BUDIYONO', 'no_kendaraan' => 'AA 1339 BF', 'perusahaan_id' => 33, 'trayek_id' => 14],
['pemilik' => 'BUDIYONO', 'no_kendaraan' => 'AA 1320 BF', 'perusahaan_id' => 33, 'trayek_id' => 14],
['pemilik' => 'NGADIMAN', 'no_kendaraan' => 'AA 1282 BF', 'perusahaan_id' => 33, 'trayek_id' => 14],
['pemilik' => 'NGADIMAN', 'no_kendaraan' => 'AA 1306 BF', 'perusahaan_id' => 33, 'trayek_id' => 14],
['pemilik' => 'ROCHMADI', 'no_kendaraan' => 'AA 1274 BF', 'perusahaan_id' => 33, 'trayek_id' => 14],
['pemilik' => 'ROCHMADI', 'no_kendaraan' => 'AA 1275 BF', 'perusahaan_id' => 33, 'trayek_id' => 14],
['pemilik' => 'SUGIYARTO', 'no_kendaraan' => 'AA 1186 BF', 'perusahaan_id' => 36, 'trayek_id' => 14],
['pemilik' => 'SURIPTO', 'no_kendaraan' => 'AA 1271 BF', 'perusahaan_id' => 33, 'trayek_id' => 14],
['pemilik' => 'SURIPTO', 'no_kendaraan' => 'AA 1290 BF', 'perusahaan_id' => 33, 'trayek_id' => 14],
['pemilik' => 'WALIJO', 'no_kendaraan' => 'AA 1021 CF', 'perusahaan_id' => 33, 'trayek_id' => 14],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1016 CF', 'perusahaan_id' => 1, 'trayek_id' => 14],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1023 CF', 'perusahaan_id' => 1, 'trayek_id' => 14],
['pemilik' => 'H AHMAD SARNO', 'no_kendaraan' => 'AA 1051 CF', 'perusahaan_id' => 37, 'trayek_id' => 15],
['pemilik' => 'H SPYAN', 'no_kendaraan' => 'AA 1376 BF', 'perusahaan_id' => 33, 'trayek_id' => 15],
['pemilik' => 'JAFAR', 'no_kendaraan' => 'AA 1032 CF', 'perusahaan_id' => 33, 'trayek_id' => 15],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1043 CF', 'perusahaan_id' => 3, 'trayek_id' => 15],
['pemilik' => 'MUCH DAWAMI ', 'no_kendaraan' => 'AA 1383 BF', 'perusahaan_id' => 33, 'trayek_id' => 15],
['pemilik' => 'MUCH DAWAMI ', 'no_kendaraan' => 'AA 1395 BF', 'perusahaan_id' => 33, 'trayek_id' => 15],
['pemilik' => 'MUCH DAWAMI ', 'no_kendaraan' => 'AA 1393 BF', 'perusahaan_id' => 33, 'trayek_id' => 15],
['pemilik' => 'PAIMAN', 'no_kendaraan' => 'AA 1053 BF', 'perusahaan_id' => 33, 'trayek_id' => 15],
['pemilik' => 'ROCHMADI', 'no_kendaraan' => 'AA 1275 BF', 'perusahaan_id' => 33, 'trayek_id' => 15],
['pemilik' => 'SARNO AHMAD', 'no_kendaraan' => 'AA 1390 BF', 'perusahaan_id' => 38, 'trayek_id' => 15],
['pemilik' => 'SURAHMAN', 'no_kendaraan' => 'AA 1062 CF', 'perusahaan_id' => 33, 'trayek_id' => 15],
['pemilik' => 'SURAHMAN', 'no_kendaraan' => 'AA 1048 CF', 'perusahaan_id' => 33, 'trayek_id' => 15],
['pemilik' => 'SUTRISN', 'no_kendaraan' => 'AA 1397 BF', 'perusahaan_id' => 33, 'trayek_id' => 15],
['pemilik' => 'SUWARDI', 'no_kendaraan' => 'AA 1389 BF', 'perusahaan_id' => 33, 'trayek_id' => 15],
['pemilik' => 'SUWARDI', 'no_kendaraan' => 'AA 1396 BF', 'perusahaan_id' => 31, 'trayek_id' => 15],
['pemilik' => 'SUWARDI', 'no_kendaraan' => 'AA 1391 BF', 'perusahaan_id' => 31, 'trayek_id' => 15],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1213 OF', 'perusahaan_id' => 6, 'trayek_id' => 16],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1266 BF', 'perusahaan_id' => 6, 'trayek_id' => 16],
['pemilik' => 'MAD TAHRIL', 'no_kendaraan' => 'AA 1261 BF', 'perusahaan_id' => 33, 'trayek_id' => 16],
['pemilik' => 'MAD TAHRIL', 'no_kendaraan' => 'AA 1277 BF', 'perusahaan_id' => 33, 'trayek_id' => 16],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1469 OF', 'perusahaan_id' => 6, 'trayek_id' => 16],
['pemilik' => 'MUSTOFA', 'no_kendaraan' => 'AA 1280 CF', 'perusahaan_id' => 33, 'trayek_id' => 16],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1293 BF', 'perusahaan_id' => 6, 'trayek_id' => 16],
['pemilik' => 'SLAMET YUSUF', 'no_kendaraan' => 'AA 1055 BF', 'perusahaan_id' => 33, 'trayek_id' => 16],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1214 OF', 'perusahaan_id' => 26, 'trayek_id' => 16],
['pemilik' => 'SUROTO', 'no_kendaraan' => 'AA 1254 CF', 'perusahaan_id' => 33, 'trayek_id' => 16],
['pemilik' => 'TUTI RAHAYU', 'no_kendaraan' => 'AA 1018 CF', 'perusahaan_id' => 33, 'trayek_id' => 16],
['pemilik' => 'TUTI RAHAYU', 'no_kendaraan' => 'AA 1042 BF', 'perusahaan_id' => 33, 'trayek_id' => 16],
['pemilik' => 'AGUS SUGIARTO', 'no_kendaraan' => 'AA 1033 BF', 'perusahaan_id' => 4, 'trayek_id' => 17],
['pemilik' => 'BARIYAH SUKHARI', 'no_kendaraan' => 'AA 1217 CF', 'perusahaan_id' => 4, 'trayek_id' => 17],
['pemilik' => 'KIMONO', 'no_kendaraan' => 'AA 1239 CF', 'perusahaan_id' => 4, 'trayek_id' => 17],
['pemilik' => 'SUPARMAN', 'no_kendaraan' => 'AA 1291 CF', 'perusahaan_id' => 4, 'trayek_id' => 17],
['pemilik' => 'SUPARTO', 'no_kendaraan' => 'AA 1256 CF', 'perusahaan_id' => 4, 'trayek_id' => 17],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1036 BF', 'perusahaan_id' => 6, 'trayek_id' => 17],
['pemilik' => 'DEWI KURNIAWATI', 'no_kendaraan' => 'AA 1040 CF', 'perusahaan_id' => 39, 'trayek_id' => 18],
['pemilik' => 'DEWI KURNIAWATI', 'no_kendaraan' => 'AA 1038 CF', 'perusahaan_id' => 39, 'trayek_id' => 18],
['pemilik' => 'M WIDIYANTO', 'no_kendaraan' => 'AA 1034 CF', 'perusahaan_id' => 31, 'trayek_id' => 18],
['pemilik' => 'DEWI KURNIAWATI', 'no_kendaraan' => 'AA 1460 OF', 'perusahaan_id' => 39, 'trayek_id' => 18],
['pemilik' => 'DEWI KURNIAWATI', 'no_kendaraan' => 'AA 1030 CF', 'perusahaan_id' => 39, 'trayek_id' => 18],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1033 CF', 'perusahaan_id' => 40, 'trayek_id' => 18],
['pemilik' => 'ADI SUSILO', 'no_kendaraan' => 'AA 1381 BF', 'perusahaan_id' => 35, 'trayek_id' => 19],
['pemilik' => 'BUDIYONO ', 'no_kendaraan' => 'AA   BF', 'perusahaan_id' => 35, 'trayek_id' => 19],
['pemilik' => 'HJ ENDAR S SETYO', 'no_kendaraan' => 'AA 1380 BF', 'perusahaan_id' => 35, 'trayek_id' => 19],
['pemilik' => 'MARSUS SPD', 'no_kendaraan' => 'AA 1378 BF', 'perusahaan_id' => 35, 'trayek_id' => 19],
['pemilik' => 'MUKHAMDI', 'no_kendaraan' => 'AA 1360 BF', 'perusahaan_id' => 35, 'trayek_id' => 19],
['pemilik' => 'MURIN HADI S', 'no_kendaraan' => 'AA 1359 BF', 'perusahaan_id' => 35, 'trayek_id' => 19],
['pemilik' => 'PAIJO SANJOYO', 'no_kendaraan' => 'AA 1361 BF', 'perusahaan_id' => 35, 'trayek_id' => 19],
['pemilik' => 'RIYADIN', 'no_kendaraan' => 'AA 1362 BF', 'perusahaan_id' => 35, 'trayek_id' => 19],
['pemilik' => 'SUPARLAN', 'no_kendaraan' => 'AA 1379 BF', 'perusahaan_id' => 35, 'trayek_id' => 19],
['pemilik' => 'SYAIFUDIN', 'no_kendaraan' => 'AA 1358 BF', 'perusahaan_id' => 35, 'trayek_id' => 19],
['pemilik' => 'SUMAJI', 'no_kendaraan' => 'AA 1264 CF', 'perusahaan_id' => 12, 'trayek_id' => 20],
['pemilik' => 'SUMAJI', 'no_kendaraan' => 'AA 1258 CF', 'perusahaan_id' => 12, 'trayek_id' => 20],
['pemilik' => 'SUMAJI', 'no_kendaraan' => 'AA 1280 CF', 'perusahaan_id' => 12, 'trayek_id' => 20],
['pemilik' => 'SUMAJI', 'no_kendaraan' => 'AA 1246 CF', 'perusahaan_id' => 12, 'trayek_id' => 20],
['pemilik' => 'SUMAJI', 'no_kendaraan' => 'AA 1253 CF', 'perusahaan_id' => 12, 'trayek_id' => 20],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1247 CF', 'perusahaan_id' => 1, 'trayek_id' => 20],
['pemilik' => 'SUMAJI', 'no_kendaraan' => 'AA 1259 CF', 'perusahaan_id' => 12, 'trayek_id' => 20],
['pemilik' => 'SUMAJI', 'no_kendaraan' => 'AA 1269 CF', 'perusahaan_id' => 12, 'trayek_id' => 20],
['pemilik' => 'WARNO', 'no_kendaraan' => 'AA 1245 CF', 'perusahaan_id' => 33, 'trayek_id' => 20],
['pemilik' => 'BASTOMI', 'no_kendaraan' => 'AA 1783 CF', 'perusahaan_id' => 31, 'trayek_id' => 21],
['pemilik' => 'BASTOMI', 'no_kendaraan' => 'AA 1250 CF', 'perusahaan_id' => 31, 'trayek_id' => 21],
['pemilik' => 'DALDIRI', 'no_kendaraan' => 'AA 1241 CF', 'perusahaan_id' => 38, 'trayek_id' => 21],
['pemilik' => 'FUAD ZAENUDIN', 'no_kendaraan' => 'AA 1297 CF', 'perusahaan_id' => 38, 'trayek_id' => 21],
['pemilik' => 'HADI SUPRIYANTO', 'no_kendaraan' => 'AA 1305 CF', 'perusahaan_id' => 33, 'trayek_id' => 21],
['pemilik' => 'KHAFID USMAN', 'no_kendaraan' => 'AA 1248 CF', 'perusahaan_id' => 33, 'trayek_id' => 21],
['pemilik' => 'SLAMET', 'no_kendaraan' => 'AA 1251 CF', 'perusahaan_id' => 31, 'trayek_id' => 21],
['pemilik' => 'SUKISMAN', 'no_kendaraan' => 'AA 1350 CF', 'perusahaan_id' => 33, 'trayek_id' => 21],
['pemilik' => "H MUH MA'SUM", 'no_kendaraan' => 'AA 1266 CF', 'perusahaan_id' => 41, 'trayek_id' => 22],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1286 OF', 'perusahaan_id' => 4, 'trayek_id' => 22],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1412 OF', 'perusahaan_id' => 4, 'trayek_id' => 22],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1249 CF', 'perusahaan_id' => 4, 'trayek_id' => 22],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1190 OF', 'perusahaan_id' => 4, 'trayek_id' => 22],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1288 CF', 'perusahaan_id' => 4, 'trayek_id' => 22],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1147 OF', 'perusahaan_id' => 6, 'trayek_id' => 22],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1255 CF', 'perusahaan_id' => 6, 'trayek_id' => 22],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1271 CF', 'perusahaan_id' => 30, 'trayek_id' => 22],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1148 OF', 'perusahaan_id' => 6, 'trayek_id' => 23],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1174 OF', 'perusahaan_id' => 6, 'trayek_id' => 23],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1408 OF', 'perusahaan_id' => 6, 'trayek_id' => 23],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1259 CF', 'perusahaan_id' => 6, 'trayek_id' => 23],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1352 CF', 'perusahaan_id' => 6, 'trayek_id' => 23],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1383 OF', 'perusahaan_id' => 6, 'trayek_id' => 23],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1355 CF', 'perusahaan_id' => 6, 'trayek_id' => 23],
['pemilik' => 'SUBARDI ', 'no_kendaraan' => 'AA 1361 CF', 'perusahaan_id' => 33, 'trayek_id' => 23],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1343 CF', 'perusahaan_id' => 6, 'trayek_id' => 23],
['pemilik' => 'MASDUQI', 'no_kendaraan' => 'AA 1387 CF', 'perusahaan_id' => 6, 'trayek_id' => 23],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1310 OF', 'perusahaan_id' => 4, 'trayek_id' => 24],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1351 CF', 'perusahaan_id' => 4, 'trayek_id' => 24],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1380 CF', 'perusahaan_id' => 4, 'trayek_id' => 24],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1192 OF', 'perusahaan_id' => 4, 'trayek_id' => 24],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1299 OF', 'perusahaan_id' => 4, 'trayek_id' => 24],
['pemilik' => 'PRIYO HANDOKO, ST', 'no_kendaraan' => 'AA 1526 CF', 'perusahaan_id' => 42, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1727 BF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1529 DF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7381 OF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7536 OF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'SUWARNO', 'no_kendaraan' => 'AA 1641 BF', 'perusahaan_id' => 43, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7283 OF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1632 CF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1637 BF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1578 BF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7274 OF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1401 BF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7248 OF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7282 OF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1476 BF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1426 BF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7298 OF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1507 BF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'SUPRIYADI ', 'no_kendaraan' => 'AA 1467 BF', 'perusahaan_id' => 44, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1576 CF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'SUTARTI ', 'no_kendaraan' => 'AA 1481 BF', 'perusahaan_id' => 45, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1716 BF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7365 OF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'PRIYO HANDOKO, ST', 'no_kendaraan' => 'AA 1526 CF', 'perusahaan_id' => 42, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7347 OF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 7154 OF', 'perusahaan_id' => 3, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7297 OF', 'perusahaan_id' => 4, 'trayek_id' => 25],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => ' 7280 OF', 'perusahaan_id' => 4, 'trayek_id' => 26],
['pemilik' => 'DIANTO ', 'no_kendaraan' => 'AA 1546 BF', 'perusahaan_id' => 46, 'trayek_id' => 26],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7344 OF', 'perusahaan_id' => 4, 'trayek_id' => 26],
['pemilik' => 'HARJONO ', 'no_kendaraan' => 'AA 1622 CF', 'perusahaan_id' => 47, 'trayek_id' => 26],
['pemilik' => 'KARSONO ', 'no_kendaraan' => 'AA 1597 BF', 'perusahaan_id' => 48, 'trayek_id' => 26],
['pemilik' => 'KARSONO ', 'no_kendaraan' => 'AA 1708 BF', 'perusahaan_id' => 48, 'trayek_id' => 26],
['pemilik' => 'M BAKRI ', 'no_kendaraan' => 'AA 1713 BF', 'perusahaan_id' => 49, 'trayek_id' => 26],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7426 OF', 'perusahaan_id' => 4, 'trayek_id' => 26],
['pemilik' => 'M SYAHID ', 'no_kendaraan' => 'AA 1429 CF', 'perusahaan_id' => 50, 'trayek_id' => 26],
['pemilik' => 'SAEFUL BAKRI ', 'no_kendaraan' => 'AA 1501 BF', 'perusahaan_id' => 51, 'trayek_id' => 26],
['pemilik' => 'SOEFI ROHMAT ', 'no_kendaraan' => 'AA 1453 BF', 'perusahaan_id' => 51, 'trayek_id' => 26],
['pemilik' => 'SOEFI ROHMAT ', 'no_kendaraan' => 'AA 1622 BF', 'perusahaan_id' => 52, 'trayek_id' => 26],
['pemilik' => 'SOEFI ROHMAT ', 'no_kendaraan' => 'AA 1455 BF', 'perusahaan_id' => 52, 'trayek_id' => 26],
['pemilik' => 'SUKUR ROHMAN ', 'no_kendaraan' => 'AA 1586 BF', 'perusahaan_id' => 53, 'trayek_id' => 26],
['pemilik' => 'SUKUR ROHMAN ', 'no_kendaraan' => 'AA 1696 BF', 'perusahaan_id' => 53, 'trayek_id' => 26],
['pemilik' => 'SUMINEM ', 'no_kendaraan' => 'AA 1478 BF', 'perusahaan_id' => 52, 'trayek_id' => 26],
['pemilik' => 'SUYIPTO ', 'no_kendaraan' => 'AA 1403 BF', 'perusahaan_id' => 54, 'trayek_id' => 26],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7027 OF', 'perusahaan_id' => 4, 'trayek_id' => 26],
['pemilik' => 'TJIAN LIANG ', 'no_kendaraan' => 'AA 1491 BF', 'perusahaan_id' => 55, 'trayek_id' => 26],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7438 OF', 'perusahaan_id' => 4, 'trayek_id' => 26],
['pemilik' => 'TUGIMAN ', 'no_kendaraan' => 'AA 1426 CF', 'perusahaan_id' => 56, 'trayek_id' => 26],
['pemilik' => 'TUGIMAN ', 'no_kendaraan' => 'AA 1471 CF', 'perusahaan_id' => 56, 'trayek_id' => 26],
['pemilik' => 'TUGIMAN ', 'no_kendaraan' => 'AA 1426 CF', 'perusahaan_id' => 56, 'trayek_id' => 26],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1418 BF', 'perusahaan_id' => 4, 'trayek_id' => 26],
['pemilik' => 'ZAENUDIN ', 'no_kendaraan' => 'AA 1540 BF', 'perusahaan_id' => 57, 'trayek_id' => 26],
['pemilik' => 'ZAENUDIN ', 'no_kendaraan' => 'AA 1527 BF', 'perusahaan_id' => 57, 'trayek_id' => 26],
['pemilik' => 'ZAENUDIN ', 'no_kendaraan' => 'AA 1496 BF', 'perusahaan_id' => 57, 'trayek_id' => 26],
['pemilik' => 'ZAENUDIN ', 'no_kendaraan' => 'AA 1564 BF', 'perusahaan_id' => 57, 'trayek_id' => 26],
['pemilik' => 'ZAENUDIN ', 'no_kendaraan' => 'AA 1447 BF', 'perusahaan_id' => 57, 'trayek_id' => 26],
['pemilik' => 'ZAENUDIN ', 'no_kendaraan' => 'AA 1407 BF', 'perusahaan_id' => 57, 'trayek_id' => 26],
['pemilik' => 'ZAENUDIN ', 'no_kendaraan' => 'AA 1452 BF', 'perusahaan_id' => 57, 'trayek_id' => 26],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 7343 OF', 'perusahaan_id' => 58, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7329 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7315 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1563 CF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7151 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7484 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'H. BADRUN', 'no_kendaraan' => 'AA 7049 OF', 'perusahaan_id' => 59, 'trayek_id' => 27],
['pemilik' => 'H. BADRUN', 'no_kendaraan' => 'AA 7050 OF', 'perusahaan_id' => 59, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7205 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1710 BF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1545 CF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1406 BF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7490 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1636 BF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7090 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7450 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7089 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'EKO PURWANTONO', 'no_kendaraan' => 'AA 1523 CF', 'perusahaan_id' => 60, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7143 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1714 BF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1660 CF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1634 CF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7032 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7176 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7172 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7330 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1492 BF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'NIYEM AL NIYO ', 'no_kendaraan' => 'AA 1422 BF', 'perusahaan_id' => 3, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1516 BF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'SUPRIYANTO ', 'no_kendaraan' => 'AA 1709 BF', 'perusahaan_id' => 61, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1582 CF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7093 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7167 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 7388 OF', 'perusahaan_id' => 58, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7078 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 7135 OF', 'perusahaan_id' => 58, 'trayek_id' => 27],
['pemilik' => 'ZAENUDIN ', 'no_kendaraan' => 'AA 1449 BF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'ZAENUDIN ', 'no_kendaraan' => 'AA 1450 BF', 'perusahaan_id' => 62, 'trayek_id' => 27],
['pemilik' => 'M SUBHAN', 'no_kendaraan' => 'AA 7478 OF', 'perusahaan_id' => 58, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 7174 OF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'EKO PURWANTONO', 'no_kendaraan' => 'AA 7424 OF', 'perusahaan_id' => 60, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1523 DF', 'perusahaan_id' => 4, 'trayek_id' => 27],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1425 CF', 'perusahaan_id' => 4, 'trayek_id' => 28],
['pemilik' => 'MUCH CHOIRI', 'no_kendaraan' => 'AA 1596 CF', 'perusahaan_id' => 4, 'trayek_id' => 28],
['pemilik' => 'SUMERU', 'no_kendaraan' => 'AA 1315 CF', 'perusahaan_id' => 33, 'trayek_id' => 29],
['pemilik' => 'WINARTI ', 'no_kendaraan' => 'AA 1334 CF', 'perusahaan_id' => 63, 'trayek_id' => 29],
];



DB::table('kendaraans')->insert($data);
    }
}
